# This file was auto-generated by Fern from our API Definition.

from .ephemeral_prompt_cache_config import EphemeralPromptCacheConfig

ComponentsSchemasEphemeralPromptCacheConfig = EphemeralPromptCacheConfig
