# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .vellum_document_request import VellumDocumentRequest


class DocumentVellumValueRequest(UniversalBaseModel):
    """
    A base Vellum primitive value representing a document.
    """

    type: typing.Literal["DOCUMENT"] = "DOCUMENT"
    value: typing.Optional[VellumDocumentRequest] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
