# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .logical_operator import LogicalOperator
from .metadata_filter_rule_combinator import MetadataFilterRuleCombinator


class MetadataFilterConfigRequest(UniversalBaseModel):
    """
    A deprecated pattern for filtering on metadata. Please use MetadataFilters instead.
    """

    combinator: typing.Optional[MetadataFilterRuleCombinator] = None
    negated: typing.Optional[bool] = None
    rules: typing.Optional[typing.List["MetadataFilterRuleRequest"]] = None
    field: typing.Optional[str] = None
    operator: typing.Optional[LogicalOperator] = None
    value: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .metadata_filter_rule_request import MetadataFilterRuleRequest  # noqa: E402, F401, I001

update_forward_refs(MetadataFilterConfigRequest)
