# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .chat_message import ChatMessage


class MetricDefinitionInput_String(UniversalBaseModel):
    type: typing.Literal["STRING"] = "STRING"
    name: str
    value: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class MetricDefinitionInput_Json(UniversalBaseModel):
    type: typing.Literal["JSON"] = "JSON"
    name: str
    value: typing.Optional[typing.Optional[typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class MetricDefinitionInput_ChatHistory(UniversalBaseModel):
    type: typing.Literal["CHAT_HISTORY"] = "CHAT_HISTORY"
    name: str
    value: typing.List[ChatMessage]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class MetricDefinitionInput_Number(UniversalBaseModel):
    type: typing.Literal["NUMBER"] = "NUMBER"
    name: str
    value: float

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


MetricDefinitionInput = typing.Union[
    MetricDefinitionInput_String,
    MetricDefinitionInput_Json,
    MetricDefinitionInput_ChatHistory,
    MetricDefinitionInput_Number,
]
