# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .chat_message_request import ChatMessageRequest
from .vellum_audio_request import VellumAudioRequest
from .vellum_document_request import VellumDocumentRequest
from .vellum_image_request import VellumImageRequest
from .vellum_video_request import VellumVideoRequest


class NamedScenarioInputRequest_String(UniversalBaseModel):
    type: typing.Literal["STRING"] = "STRING"
    value: typing.Optional[str] = None
    name: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NamedScenarioInputRequest_Json(UniversalBaseModel):
    type: typing.Literal["JSON"] = "JSON"
    value: typing.Optional[typing.Optional[typing.Any]] = None
    name: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NamedScenarioInputRequest_ChatHistory(UniversalBaseModel):
    type: typing.Literal["CHAT_HISTORY"] = "CHAT_HISTORY"
    value: typing.Optional[typing.List[ChatMessageRequest]] = None
    name: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NamedScenarioInputRequest_Audio(UniversalBaseModel):
    type: typing.Literal["AUDIO"] = "AUDIO"
    value: VellumAudioRequest
    name: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NamedScenarioInputRequest_Video(UniversalBaseModel):
    type: typing.Literal["VIDEO"] = "VIDEO"
    value: VellumVideoRequest
    name: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NamedScenarioInputRequest_Image(UniversalBaseModel):
    type: typing.Literal["IMAGE"] = "IMAGE"
    value: VellumImageRequest
    name: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NamedScenarioInputRequest_Document(UniversalBaseModel):
    type: typing.Literal["DOCUMENT"] = "DOCUMENT"
    value: VellumDocumentRequest
    name: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


NamedScenarioInputRequest = typing.Union[
    NamedScenarioInputRequest_String,
    NamedScenarioInputRequest_Json,
    NamedScenarioInputRequest_ChatHistory,
    NamedScenarioInputRequest_Audio,
    NamedScenarioInputRequest_Video,
    NamedScenarioInputRequest_Image,
    NamedScenarioInputRequest_Document,
]
