# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .chat_message import ChatMessage
from .vellum_audio import VellumAudio
from .vellum_document import VellumDocument
from .vellum_image import VellumImage
from .vellum_video import VellumVideo


class ScenarioInput_String(UniversalBaseModel):
    type: typing.Literal["STRING"] = "STRING"
    value: typing.Optional[str] = None
    input_variable_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ScenarioInput_Json(UniversalBaseModel):
    type: typing.Literal["JSON"] = "JSON"
    value: typing.Optional[typing.Optional[typing.Any]] = None
    input_variable_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ScenarioInput_ChatHistory(UniversalBaseModel):
    type: typing.Literal["CHAT_HISTORY"] = "CHAT_HISTORY"
    value: typing.Optional[typing.List[ChatMessage]] = None
    input_variable_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ScenarioInput_Audio(UniversalBaseModel):
    type: typing.Literal["AUDIO"] = "AUDIO"
    value: typing.Optional[VellumAudio] = None
    input_variable_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ScenarioInput_Video(UniversalBaseModel):
    type: typing.Literal["VIDEO"] = "VIDEO"
    value: typing.Optional[VellumVideo] = None
    input_variable_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ScenarioInput_Image(UniversalBaseModel):
    type: typing.Literal["IMAGE"] = "IMAGE"
    value: typing.Optional[VellumImage] = None
    input_variable_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ScenarioInput_Document(UniversalBaseModel):
    type: typing.Literal["DOCUMENT"] = "DOCUMENT"
    value: typing.Optional[VellumDocument] = None
    input_variable_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


ScenarioInput = typing.Union[
    ScenarioInput_String,
    ScenarioInput_Json,
    ScenarioInput_ChatHistory,
    ScenarioInput_Audio,
    ScenarioInput_Video,
    ScenarioInput_Image,
    ScenarioInput_Document,
]
