# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .vellum_audio_request import VellumAudioRequest


class WorkflowRequestAudioInputRequest(UniversalBaseModel):
    """
    The input for an audio variable in a Workflow.
    """

    name: str = pydantic.Field()
    """
    The variable's name, as defined in the Workflow.
    """

    type: typing.Literal["AUDIO"] = "AUDIO"
    value: VellumAudioRequest

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
