name: Run Evaluation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Push workflow to Vellum
        run: |
          cd examples/evals/github_actions
          poetry run vellum workflows push github_actions
        env:
          VELLUM_API_KEY: ${{ secrets.VELLUM_API_KEY }}

      - name: Run evaluation
        run: |
          cd examples/evals/github_actions
          poetry run python eval.py
        env:
          VELLUM_API_KEY: ${{ secrets.VELLUM_API_KEY }}

      - name: Report results
        run: echo "Evaluation completed - check logs for results"
