# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .vellum_value import VellumValue


class ArrayInput(UniversalBaseModel):
    """
    A user input representing a Vellum Array value
    """

    name: str = pydantic.Field()
    """
    The variable's name
    """

    type: typing.Literal["ARRAY"] = "ARRAY"
    value: typing.List[VellumValue]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
