# This file was auto-generated by Fern from our API Definition.

import typing

from .array_input import ArrayInput
from .chat_history_input import ChatHistoryInput
from .code_executor_secret_input import CodeExecutorSecretInput
from .error_input import ErrorInput
from .function_call_input import FunctionCallInput
from .json_input import JsonInput
from .number_input import NumberInput
from .search_results_input import SearchResultsInput
from .string_input import StringInput

CodeExecutorInput = typing.Union[
    StringInput,
    JsonInput,
    ChatHistoryInput,
    NumberInput,
    SearchResultsInput,
    ErrorInput,
    ArrayInput,
    FunctionCallInput,
    CodeExecutorSecretInput,
]
