# This file was auto-generated by Fern from our API Definition.

import typing
from pydantic import Field

from .delimiter_chunking_request import DelimiterChunkingRequest
from .reducto_chunking_request import ReductoChunkingRequest
from .sentence_chunking_request import SentenceChunkingRequest
from .token_overlapping_window_chunking_request import TokenOverlappingWindowChunkingRequest

DocumentIndexChunkingRequest = typing.Annotated[
    typing.Union[
        ReductoChunkingRequest, SentenceChunkingRequest, TokenOverlappingWindowChunkingRequest, DelimiterChunkingRequest
    ],
    Field(discriminator="chunker_name")
]
