# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .execute_workflow_workflow_result_event import ExecuteWorkflowWorkflowResultEvent


class ExecuteWorkflowResponse(UniversalBaseModel):
    execution_id: str
    run_id: typing.Optional[str] = None
    external_id: typing.Optional[str] = None
    data: ExecuteWorkflowWorkflowResultEvent

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .array_vellum_value import ArrayVellumValue  # noqa: E402, F401, I001

update_forward_refs(ExecuteWorkflowResponse)
