# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .chat_message import ChatMessage
from .function_call import FunctionCall
from .search_result import SearchResult
from .string_vellum_value import StringVellumValue
from .vellum_error import VellumError
from .workflow_node_result_event_state import WorkflowNodeResultEventState


class NodeOutputCompiledValue_String(UniversalBaseModel):
    type: typing.Literal["STRING"] = "STRING"
    value: typing.Optional[str] = None
    node_output_id: str
    state: typing.Optional[WorkflowNodeResultEventState] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NodeOutputCompiledValue_Number(UniversalBaseModel):
    type: typing.Literal["NUMBER"] = "NUMBER"
    value: typing.Optional[float] = None
    node_output_id: str
    state: typing.Optional[WorkflowNodeResultEventState] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NodeOutputCompiledValue_Json(UniversalBaseModel):
    type: typing.Literal["JSON"] = "JSON"
    value: typing.Optional[typing.Optional[typing.Any]] = None
    node_output_id: str
    state: typing.Optional[WorkflowNodeResultEventState] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NodeOutputCompiledValue_ChatHistory(UniversalBaseModel):
    type: typing.Literal["CHAT_HISTORY"] = "CHAT_HISTORY"
    value: typing.Optional[typing.List[ChatMessage]] = None
    node_output_id: str
    state: typing.Optional[WorkflowNodeResultEventState] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NodeOutputCompiledValue_SearchResults(UniversalBaseModel):
    type: typing.Literal["SEARCH_RESULTS"] = "SEARCH_RESULTS"
    value: typing.Optional[typing.List[SearchResult]] = None
    node_output_id: str
    state: typing.Optional[WorkflowNodeResultEventState] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NodeOutputCompiledValue_Error(UniversalBaseModel):
    type: typing.Literal["ERROR"] = "ERROR"
    value: typing.Optional[VellumError] = None
    node_output_id: str
    state: typing.Optional[WorkflowNodeResultEventState] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NodeOutputCompiledValue_Array(UniversalBaseModel):
    type: typing.Literal["ARRAY"] = "ARRAY"
    value: typing.Optional[typing.List["VellumValue"]] = None
    node_output_id: str
    state: typing.Optional[WorkflowNodeResultEventState] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .array_vellum_value import ArrayVellumValue  # noqa: E402, F401, I001
from .vellum_value import VellumValue  # noqa: E402, F401, I001


class NodeOutputCompiledValue_FunctionCall(UniversalBaseModel):
    type: typing.Literal["FUNCTION_CALL"] = "FUNCTION_CALL"
    value: typing.Optional[FunctionCall] = None
    node_output_id: str
    state: typing.Optional[WorkflowNodeResultEventState] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NodeOutputCompiledValue_Thinking(UniversalBaseModel):
    type: typing.Literal["THINKING"] = "THINKING"
    value: typing.Optional[StringVellumValue] = None
    node_output_id: str
    state: typing.Optional[WorkflowNodeResultEventState] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


NodeOutputCompiledValue = typing.Union[
    NodeOutputCompiledValue_String,
    NodeOutputCompiledValue_Number,
    NodeOutputCompiledValue_Json,
    NodeOutputCompiledValue_ChatHistory,
    NodeOutputCompiledValue_SearchResults,
    NodeOutputCompiledValue_Error,
    NodeOutputCompiledValue_Array,
    NodeOutputCompiledValue_FunctionCall,
    NodeOutputCompiledValue_Thinking,
]
update_forward_refs(NodeOutputCompiledValue_Array)
