# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .release_review_reviewer import ReleaseReviewReviewer
from .release_review_state import ReleaseReviewState


class SlimReleaseReview(UniversalBaseModel):
    id: str
    created: dt.datetime
    reviewer: ReleaseReviewReviewer
    state: ReleaseReviewState

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
