# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .integration import Integration


class SlimToolDefinition_Composio(UniversalBaseModel):
    provider: typing.Literal["COMPOSIO"] = "COMPOSIO"
    integration: Integration
    name: str
    label: str
    description: str
    toolkit_version: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


SlimToolDefinition = SlimToolDefinition_Composio
