# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .condition_combinator import ConditionCombinator
from .logical_operator import LogicalOperator


class VellumValueLogicalExpressionRequest_LogicalCondition(UniversalBaseModel):
    type: typing.Literal["LOGICAL_CONDITION"] = "LOGICAL_CONDITION"
    lhs_variable: "VellumValueRequest"
    operator: LogicalOperator
    rhs_variable: "VellumValueRequest"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .vellum_value_request import VellumValueRequest  # noqa: E402, F401, I001


class VellumValueLogicalExpressionRequest_LogicalConditionGroup(UniversalBaseModel):
    type: typing.Literal["LOGICAL_CONDITION_GROUP"] = "LOGICAL_CONDITION_GROUP"
    conditions: typing.List["VellumValueLogicalExpressionRequest"]
    combinator: ConditionCombinator
    negated: bool

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .array_vellum_value_request import ArrayVellumValueRequest  # noqa: E402, F401, I001
from .vellum_value_logical_condition_group_request import VellumValueLogicalConditionGroupRequest  # noqa: E402, F401, I001

VellumValueLogicalExpressionRequest = typing.Union[
    VellumValueLogicalExpressionRequest_LogicalCondition, VellumValueLogicalExpressionRequest_LogicalConditionGroup
]
update_forward_refs(VellumValueLogicalExpressionRequest_LogicalCondition)
update_forward_refs(VellumValueLogicalExpressionRequest_LogicalConditionGroup)
