# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .workflow_state_meta_node_execution_cache import WorkflowStateMetaNodeExecutionCache
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class WorkflowStateMeta(UniversalBaseModel):
    node_outputs: typing.Dict[str, typing.Optional[typing.Any]]
    node_execution_cache: WorkflowStateMetaNodeExecutionCache

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
