# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .chat_message import ChatMessage
from .function_call import FunctionCall
from .search_result import SearchResult
from .vellum_audio import VellumAudio
from .vellum_document import VellumDocument
from .vellum_error import VellumError
from .vellum_image import VellumImage
from .vellum_video import VellumVideo


class WorkflowOutput_String(UniversalBaseModel):
    type: typing.Literal["STRING"] = "STRING"
    id: str
    name: str
    value: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class WorkflowOutput_Number(UniversalBaseModel):
    type: typing.Literal["NUMBER"] = "NUMBER"
    id: str
    name: str
    value: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class WorkflowOutput_Json(UniversalBaseModel):
    type: typing.Literal["JSON"] = "JSON"
    id: str
    name: str
    value: typing.Optional[typing.Optional[typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class WorkflowOutput_ChatHistory(UniversalBaseModel):
    type: typing.Literal["CHAT_HISTORY"] = "CHAT_HISTORY"
    id: str
    name: str
    value: typing.Optional[typing.List[ChatMessage]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class WorkflowOutput_SearchResults(UniversalBaseModel):
    type: typing.Literal["SEARCH_RESULTS"] = "SEARCH_RESULTS"
    id: str
    name: str
    value: typing.Optional[typing.List[SearchResult]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class WorkflowOutput_Array(UniversalBaseModel):
    type: typing.Literal["ARRAY"] = "ARRAY"
    id: str
    name: str
    value: typing.Optional[typing.List["VellumValue"]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .array_vellum_value import ArrayVellumValue  # noqa: E402, F401, I001
from .vellum_value import VellumValue  # noqa: E402, F401, I001


class WorkflowOutput_Error(UniversalBaseModel):
    type: typing.Literal["ERROR"] = "ERROR"
    id: str
    name: str
    value: typing.Optional[VellumError] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class WorkflowOutput_FunctionCall(UniversalBaseModel):
    type: typing.Literal["FUNCTION_CALL"] = "FUNCTION_CALL"
    id: str
    name: str
    value: typing.Optional[FunctionCall] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class WorkflowOutput_Image(UniversalBaseModel):
    type: typing.Literal["IMAGE"] = "IMAGE"
    id: str
    name: str
    value: typing.Optional[VellumImage] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class WorkflowOutput_Audio(UniversalBaseModel):
    type: typing.Literal["AUDIO"] = "AUDIO"
    id: str
    name: str
    value: typing.Optional[VellumAudio] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class WorkflowOutput_Video(UniversalBaseModel):
    type: typing.Literal["VIDEO"] = "VIDEO"
    id: str
    name: str
    value: typing.Optional[VellumVideo] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class WorkflowOutput_Document(UniversalBaseModel):
    type: typing.Literal["DOCUMENT"] = "DOCUMENT"
    id: str
    name: str
    value: typing.Optional[VellumDocument] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


WorkflowOutput = typing.Union[
    WorkflowOutput_String,
    WorkflowOutput_Number,
    WorkflowOutput_Json,
    WorkflowOutput_ChatHistory,
    WorkflowOutput_SearchResults,
    WorkflowOutput_Array,
    WorkflowOutput_Error,
    WorkflowOutput_FunctionCall,
    WorkflowOutput_Image,
    WorkflowOutput_Audio,
    WorkflowOutput_Video,
    WorkflowOutput_Document,
]
update_forward_refs(WorkflowOutput_Array)
