# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .workflow_display_icon import WorkflowDisplayIcon


class WorkflowDeploymentDisplayData(UniversalBaseModel):
    """
    Workflow Deployment display data
    """

    icon: typing.Optional[WorkflowDisplayIcon] = pydantic.Field(default=None)
    """
    The icon associated with this Workflow Deployment.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
