# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs


class WorkflowSandboxParentContext(UniversalBaseModel):
    parent: typing.Optional["ParentContext"] = None
    links: typing.Optional[typing.List["SpanLink"]] = None
    type: typing.Literal["WORKFLOW_SANDBOX"] = "WORKFLOW_SANDBOX"
    span_id: str
    sandbox_id: str
    sandbox_history_item_id: str
    scenario_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .span_link import SpanLink  # noqa: E402, I001
from .parent_context import ParentContext  # noqa: E402, I001

update_forward_refs(WorkflowSandboxParentContext)
