[project]
name = "vellum-eval-github-actions"
version = "0.1.0"
description = "GitHub Actions evaluation example for Vellum workflows"
authors = ["Vellum <devops@vellum.ai>"]
license = "MIT"
requires-python = ">=3.10,<4.0"
dependencies = [
    "vellum-ai>=1.1.2",
]

[tool.uv]
package = false
