# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.api_error import ApiError
from ..types.update_active_workspace_response import UpdateActiveWorkspaceResponse


class MisdirectedRequestError(ApiError):
    def __init__(self, body: UpdateActiveWorkspaceResponse, headers: typing.Optional[typing.Dict[str, str]] = None):
        super().__init__(status_code=421, headers=headers, body=body)
