name: ci-release-label

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

jobs:
  end-to-end-test:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'release')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.18.0"
      - name: Bootstrap poetry
        run: make setup-poetry
      - name: Install Python dependencies
        run: poetry install
      - name: Install Node.js dependencies
        run: npm install
        working-directory: ee/codegen
      - name: Run end-to-end tests
        run: python scripts/end_to_end_test.py
